version: '3.8'

services:

  # 2. Broker de Mensagens Redis
  redis:
    image: redis:7-alpine
    container_name: transportadora_redis
    restart: always

  # 3. Backend Django/DRF (Servidor Web)
  backend:
    build: .
    container_name: transportadora_backend
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 --application-close-timeout 60 core.asgi:application"
    volumes:
      - .:/transportadora_backend
      - media_data:/transportadora_backend/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  # 4. Worker do Celery (Tarefas Assíncronas)
  celery_worker:
    build: .
    container_name: transportadora_celery_worker
    command: celery -A core worker -l info
    volumes:
      - .:/transportadora_backend
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    restart: always


  # 5. Agendador do Celery Beat (Tarefas Recorrentes)
  celery_beat:
    build: .
    container_name: transportadora_celery_beat
    command: sh ./entrypoint.sh
    volumes:
      - .:/transportadora_backend
    env_file:
      - .env
    depends_on:
      - redis
    restart: always


# 6. Worker Especializado para IA (YOLO + OCR)
  celery_worker_ai:
    build: .
    container_name: transportadora_celery_ai
    # Usamos uma fila específica (-Q ai_queue) e o pool 'solo' para evitar crashes (SIGILL) do PyTorch/OpenCV no Celery
    command: celery -A core worker -l info -Q ai_queue --pool=solo --concurrency=1
    volumes:
      - .:/transportadora_backend
      - media_data:/transportadora_backend/media
    env_file:
      - .env
    environment:
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
    depends_on:
      - redis
    restart: always

volumes:
  media_data: