# Generated by Django 4.2.27 on 2025-12-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botWhatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='temp_nfe_dados',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='temp_nfe_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='temp_nfe_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
