# Generated by Django 4.2.27 on 2025-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botWhatsapp', '0002_whatsappuser_temp_nfe_dados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuser',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
